/* global window */
// Generated by scripts/generate-runtime-config.cjs.
window.__TASKPOINTS_DB__ = {
  backend: "supabase",
  url: "http://127.0.0.1:54321",
  anonKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0",
  schema: "public",
};

window.__TASKPOINTS_FLAGS__ = {
  task_timer_enabled: false,
};
